# --- DEV ENVIRONMENT (Port 8002 via Nginx) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: exam-app
        image: exam-app:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-dev
spec:
  type: NodePort
  selector:
    env: dev
  ports:
    - port: 8000
      nodePort: 30002
---
# --- RELEASE ENVIRONMENT (Port 8003 via Nginx) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-release
spec:
  replicas: 1
  selector:
    matchLabels:
      env: release
  template:
    metadata:
      labels:
        env: release
    spec:
      containers:
      - name: exam-app
        image: exam-app:release
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-release
spec:
  type: NodePort
  selector:
    env: release
  ports:
    - port: 8000
      nodePort: 30003
