name: Deploy App to Minikube

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Build & Deploy to K8s"
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create Kubernetes Manifest locally
        run: |
          cat << 'EOF' > k8s-deploy.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: exam-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: exam-app
          template:
            metadata:
              labels:
                app: exam-app
            spec:
              containers:
              - name: exam-app
                image: exam-app:v1
                imagePullPolicy: Never
                ports:
                - containerPort: 8000
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: exam-app-svc
          spec:
            type: ClusterIP
            selector:
              app: exam-app
            ports:
              - port: 8002
                targetPort: 8000
          EOF

      - name: Copy Manifest to Server
        run: scp -o StrictHostKeyChecking=no k8s-deploy.yaml root@${{ secrets.DROPLET_IP }}:/root/k8s-deploy.yaml

      - name: Build and Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "
            echo '1. Завантажуємо код застосунку...'
            rm -rf devops-exam-pt2
            git clone https://github.com/YulianSalo/devops-exam-pt2.git
            cd devops-exam-pt2
            
            echo '2. Налаштовуємо Docker...'
            eval \$(minikube docker-env)
            
            echo '3. Збираємо Docker-образ...'
            docker build -t exam-app:v1 .
            
            echo '4. Запускаємо застосунок в Kubernetes!'
            kubectl apply -f /root/k8s-deploy.yaml
            
            echo '5. Прокидаємо порт 8002 за вимогами методички...'
            pkill -f 'kubectl port-forward' || true
            nohup kubectl port-forward svc/exam-app-svc 8002:8002 --address 0.0.0.0 > /dev/null 2>&1 &
          "
