name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest
    
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_spaces_access_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_spaces_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan